// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skqbwawbkrunbyrxtlej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrcWJ3YXdia3J1bmJ5cnh0bGVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MzMwODEsImV4cCI6MjA2NzUwOTA4MX0.SnfjXOabdouWurRTFBRB5_wTycJ3TK0cLwMybMtxG80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});