// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqjfslxnakwxpxyybaot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxamZzbHhuYWt3eHB4eXliYW90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMTMwMzQsImV4cCI6MjA2Njc4OTAzNH0.8tcSg6hFENslz9UCD_X5iheeC5PSHA6qAOY1YeZhhO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});